' Gambas module file

Private conn As Connection
Private bResultado As Boolean
Private iContador As String
Private rstResultado As Result

Public Function GetAllRoles() As Result
  
  Dim sSql As String = Null
  Dim rstResultado As Result
  
  sSql = "SELECT " 
  sSql &= "ID_ROL,"  
  sSql &= "NOMBRE " 
  sSql &= "FROM ROLES "
  sSql &= "WHERE ID_ROL Not In (1) "
  sSql &= "AND ES_BAJA ='-' "
  sSql &= "ORDER BY NOMBRE ASC "
  
  conn = gConexion.ConectarDB()
  
  rstResultado = conn.Exec(sSql)
  
  Return rstResultado 
  
End
