' Gambas module file

Private conn As Connection
Private bResultado As Boolean
Private iContador As String
Private rstResultado As Result

Public Function GetUsers(sFiltro As String, sEstado As String) As Result
  
  Dim rstResultado As Result = Null
  Dim sSql As String = Null
  
  sSql = "SELECT "
  sSql &= "U.ID_USUARIO, "
  sSql &= "U.COD_USUARIO, "
  sSql &= "U.NOMBRE, "
  sSql &= "U.APELLIDO1 , "
  sSql &= "U.APELLIDO2 , "
  sSql &= "R.NOMBRE RNOMBRE, "
  sSql &= "U.ES_BAJA "
  sSql &= "FROM USUARIOS U "
  sSql &= "INNER JOIN ROLES R "
  sSql &= "ON U.ID_ROL = R.ID_ROL "
  sSql &= "WHERE (U.COD_USUARIO LIKE '%" & sFiltro & "%' OR U.NOMBRE LIKE '%" & sFiltro & "%' OR U.APELLIDO1 LIKE '%" & sFiltro & "%' OR U.APELLIDO2 LIKE '%" & sFiltro & "%' OR R.NOMBRE LIKE '%" & sFiltro & "%')"
  sSql &= "AND U.ES_BAJA LIKE '" & sEstado & "'"
  
  conn = gConexion.ConectarDB()
  
  rstResultado = conn.Exec(sSql)
  
  Return rstResultado 
  
End

Public Function GetGrid(ByRef objGridView As GridView, rstResultado As Result) As GridView 
  
  Dim i As Integer = 0
  Dim n As Integer = 0  
  Dim j As Integer = 0
  
  objGridView.Columns.Count = rstResultado.Fields.Count 
  
  For j = 0 To objGridView.Columns.Count - 1
    If j = 0 Then 
      objGridView.Columns[j].width = 0    
    Else  
      objGridView.Columns[j].Title = rstResultado.Fields[j].Name
      objGridView.Columns[j].Expand = True
      objGridView.Columns[j].Resizable = False
    Endif    
    
  Next
  '::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::   
  objGridView.Rows.Count = 0
  
  rstResultado.MoveFirst  
  Do While rstResultado.Available
    objGridView.Rows.Count = rstResultado.Count
    
    objGridView[i, 0].Text = rstResultado!ID_USUARIO
    objGridView[i, 1].Text = rstResultado!COD_USUARIO
    objGridView[i, 2].Text = rstResultado!NOMBRE
    objGridView[i, 3].Text = rstResultado!APELLIDO1
    objGridView[i, 4].Text = rstResultado!APELLIDO2
    objGridView[i, 5].Text = rstResultado!RNOMBRE
    
    If rstResultado!ES_BAJA = "+" Then
      objGridView[i, 6].Picture = gConst.picBaja
    Else
      objGridView[i, 6].Picture = gConst.picActivo
    End If
    
    Inc i
    rstResultado.MoveNext
  Loop
  Return objGridView
  
End
