' Gambas module file

Private conn As Connection
Private bResultado As Boolean
Private iContador As String
Private rstResultado As Result

Public Function GetUsers(sFiltro As String, sEstado As String) As Result
  
  Dim rstResultado As Result
  Dim sSql As String = Null
  
  sSql = "SELECT "
  sSql &= "U.ID_USUARIO, "
  sSql &= "U.COD_USUARIO, "
  sSql &= "U.NOMBRE, "
  sSql &= "U.APELLIDO1, "
  sSql &= "U.APELLIDO2, "
  sSql &= "R.NOMBRE RNOMBRE, "
  sSql &= "U.ES_BAJA "
  sSql &= "FROM USUARIOS U "
  sSql &= "INNER JOIN ROLES R "
  sSql &= "ON U.ID_ROL = R.ID_ROL "
  sSql &= "WHERE (U.COD_USUARIO LIKE '%" & sFiltro & "%' OR U.NOMBRE LIKE '%" & sFiltro & "%' OR U.APELLIDO1 LIKE '%" & sFiltro & "%' OR U.APELLIDO2 LIKE '%" & sFiltro & "%' OR R.NOMBRE LIKE '%" & sFiltro & "%')"
  sSql &= "AND U.ES_BAJA LIKE '" & sEstado & "'"
  
  conn = gConexion.ConectarDB()
  
  rstResultado = conn.Exec(sSql)
  
  Return rstResultado 
  
End

Public Sub GetGrid(ByRef objGridView As GridView, rstResultado As Result) 
  
  Dim i As Integer = 0
  
  objGridView.Columns.Count = rstResultado.Fields.Count 
  objGridView.Header = rstResultado.Fields.Count
  
  objGridView.Columns[0].width = 0
  objGridView.Columns[0].Resizable = False
  objGridView.Columns[1].Title = "COD_USUARIO"
  objGridView.Columns[1].width = 100
  objGridView.Columns[1].Resizable = False
  objGridView.Columns[2].Title = "NOMBRE"
  objGridView.Columns[2].width = 125
  objGridView.Columns[2].Resizable = False
  objGridView.Columns[3].Title = "APELLIDO1"
  objGridView.Columns[3].width = 125
  objGridView.Columns[3].Resizable = False
  objGridView.Columns[4].Title = "APELLIDO2"
  objGridView.Columns[4].width = 125
  objGridView.Columns[4].Resizable = False
  objGridView.Columns[5].Title = "ROL"
  objGridView.Columns[5].width = 125
  objGridView.Columns[5].Resizable = False
  objGridView.Columns[6].width = 25
  objGridView.Columns[6].Resizable = False
  
  '::::::::::::::::::::::::::::::::::::::::::::::::::::
  
  rstResultado.MoveFirst
  
  Do While rstResultado.Available
    objGridView.Rows.Insert(i, 1)
    objGridView[i, 0].Text = rstResultado!ID_USUARIO
    objGridView[i, 1].Text = rstResultado!COD_USUARIO
    objGridView[i, 2].Text = rstResultado!NOMBRE
    objGridView[i, 3].Text = rstResultado!APELLIDO1
    objGridView[i, 4].Text = rstResultado!APELLIDO2
    objGridView[i, 5].Text = rstResultado!RNOMBRE
    
    If rstResultado!ES_BAJA = "+" Then
      objGridView[i, 6].Picture = gConst.picBaja     
      
    Else
      objGridView[i, 6].Picture = gConst.picActivo
    End If
    
    i += 1
    rstResultado.MoveNext
  Loop
  
  ' Return objResultado
  
End
