' Gambas module file

Public picActivo As Picture = Picture.Load("images/alta.png")
Public picBaja As Picture = Picture.Load("images/baja.png")
Public picCerrado As Picture = Picture.Load("images/cerrado.png")
Public picWarn As Picture = Picture.Load("images/warning.png")
Public picCalendar As Picture = Picture.Load("images/calendar_20.png")
Public picInfo As Picture = Picture.Load("images/info_32.png")
Public picLogo As Picture = Picture.Load("images/logo.png")