' Gambas module file

Public picActivo As Picture = Picture.Load("images/alta.png")
Public picBaja As Picture = Picture.Load("images/baja.png")
Public picCerrado As Picture = Picture.Load("images/cerrado.png")
Public picWarn As Picture = Picture.Load("images/warning.png")
Public picCalendar As Picture = Picture.Load("images/calendar_20.png")
Public picDuplicado As Picture = Picture.Load("images/duplicado.png")

' Iconos para info, Warning, Critical:::::::::::::::::::::::::::::::::::::::
Public picInfo As Picture = Picture.Load("images/info_32.png")
Public picWarning As Picture = Picture.Load("images/warning_32.png")
Public picCritical As Picture = Picture.Load("images/critical_32.png")
':::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

Public picLogo As Picture = Picture.Load("images/logo.png")

' ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
' Constantes para los Storeds Procedures
Public STP_GETUSUARIOS As String = "STP_GETUSUARIOS"
