' Gambas module file

Private _idProyecto As Integer 
Private _idRequerimiento As Integer
Private _idTarea As Integer
Private _idCliente As Integer
' Log de último Status en el sistema ::::::::::::::
Private _idUsuario As Integer = 0
Private _NomUsuario As String = Null
Private _idRol As Integer = 0
Private _Rol As String = Null
Private _LastSession As String = Null
Private _LastAction As String = Null

'::::::::::::::::::::::::::::::::::::::::::::::::::

Public Function getIdProyecto() As Integer
  
  Return _idProyecto
  
End

Public Sub setIdProyecto(Value As Integer)
  
  _idProyecto = Value
  
End

Public Function getIdRequerimiento() As Integer
  
  Return _idRequerimiento
  
End

Public Sub setIdRequerimiento(Value As Integer)
  
  _idRequerimiento = Value
  
End

Public Function getIdTarea() As Integer
  
  Return _idTarea
  
End

Public Sub setIdTarea(Value As Integer)
  
  _idTarea = Value
  
End

Public Function getIdCliente() As Integer
  
  Return _idCliente 
  
End

Public Sub setIdCliente(Value As Integer)
  
  _idCliente = Value
  
End

' Detalles de usuario logado::::::::::::::::::::::::::::::::::::::::::::::::

Public Sub setUserLogged(idUsuario As Integer, nombreUser As String, idRol As Integer, Rol As String, lastSession As String, lastAction As String)
  
  _idUsuario = idUsuario
  _NomUsuario = nombreUser
  _idRol = idRol
  _Rol = Rol
  _LastAction = lastAction
  _LastSession = lastSession
  
End

Public Function getUserLogged() As String
  
  Return "Usuario: " & _NomUsuario & " - Rol: " & _Rol
  
End

Public Function getDetailsUserLogged() As String
  
  Dim resultado As String
  
  If Len(_LastSession) = 0 Then 
    resultado = Null
  Else
    resultado = "- " & _LastSession & "\r\n" & "- " & _LastAction     
  Endif
  
  Return resultado
  
End
